/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_khammash_ode_cvode_CVodeSolver_MyObserver */

#ifndef _Included_ch_ethz_khammash_ode_cvode_CVodeSolver_MyObserver
#define _Included_ch_ethz_khammash_ode_cvode_CVodeSolver_MyObserver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
