/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_khammash_ode_cvode_CVodeSolver_MyOde */

#ifndef _Included_ch_ethz_khammash_ode_cvode_CVodeSolver_MyOde
#define _Included_ch_ethz_khammash_ode_cvode_CVodeSolver_MyOde
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
