/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_khammash_ode_cvode_CVodeSolver */

#ifndef _Included_ch_ethz_khammash_ode_cvode_CVodeSolver
#define _Included_ch_ethz_khammash_ode_cvode_CVodeSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_ethz_khammash_ode_cvode_CVodeSolver
 * Method:    jni_initialize
 * Signature: (Lch/ethz/khammash/ode/BufferOdeAdapter;Lch/ethz/khammash/ode/BufferEventFunctionAdapter;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/IntBuffer;DDIIIDD)J
 */
JNIEXPORT jlong JNICALL Java_ch_ethz_khammash_ode_cvode_CVodeSolver_jni_1initialize
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jdouble, jdouble, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     ch_ethz_khammash_ode_cvode_CVodeSolver
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_khammash_ode_cvode_CVodeSolver_jni_1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_khammash_ode_cvode_CVodeSolver
 * Method:    jni_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_khammash_ode_cvode_CVodeSolver_jni_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_khammash_ode_cvode_CVodeSolver
 * Method:    jni_quick_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_khammash_ode_cvode_CVodeSolver_jni_1quick_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_khammash_ode_cvode_CVodeSolver
 * Method:    jni_integrate
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_khammash_ode_cvode_CVodeSolver_jni_1integrate
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
