/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_bhepp_ode_lsodar_LsodarDirectSolver_MyEventObserver */

#ifndef _Included_ch_ethz_bhepp_ode_lsodar_LsodarDirectSolver_MyEventObserver
#define _Included_ch_ethz_bhepp_ode_lsodar_LsodarDirectSolver_MyEventObserver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
