/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_bhepp_ode_cvode_CVodeSolver */

#ifndef _Included_ch_ethz_bhepp_ode_cvode_CVodeSolver
#define _Included_ch_ethz_bhepp_ode_cvode_CVodeSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_ethz_bhepp_ode_cvode_CVodeSolver_MULTISTEPTYPE_ADAMS
#define ch_ethz_bhepp_ode_cvode_CVodeSolver_MULTISTEPTYPE_ADAMS 1L
#undef ch_ethz_bhepp_ode_cvode_CVodeSolver_MULTISTEPTYPE_BDF
#define ch_ethz_bhepp_ode_cvode_CVodeSolver_MULTISTEPTYPE_BDF 2L
#undef ch_ethz_bhepp_ode_cvode_CVodeSolver_ITERATIONTYPE_FUNCTIONAL
#define ch_ethz_bhepp_ode_cvode_CVodeSolver_ITERATIONTYPE_FUNCTIONAL 1L
#undef ch_ethz_bhepp_ode_cvode_CVodeSolver_ITERATIONTYPE_NEWTON
#define ch_ethz_bhepp_ode_cvode_CVodeSolver_ITERATIONTYPE_NEWTON 2L
/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_initialize
 * Signature: (Lch/ethz/bhepp/ode/BufferOdeAdapter;Lch/ethz/bhepp/ode/BufferEventFunctionAdapter;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DDIIIDD)J
 */
JNIEXPORT jlong JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1initialize
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jdouble, jdouble, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_resetEventIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1resetEventIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_getEventIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1getEventIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_reinitializeOneStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1reinitializeOneStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_integrateOneStep
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1integrateOneStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_computeInterpolatedSolution
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1computeInterpolatedSolution
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_getCurrentStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1getCurrentStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_getLastStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1getLastStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_setInitStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1setInitStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_setMinStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1setMinStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_setMaxStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1setMaxStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_setStopTime
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1setStopTime
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_quick_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1quick_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_cvode_CVodeSolver
 * Method:    jni_integrate
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_cvode_CVodeSolver_jni_1integrate
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
