/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver */

#ifndef _Included_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
#define _Included_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_DORMANDPRINCE5
#define ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_DORMANDPRINCE5 1L
#undef ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_BULIRSCHSTOER
#define ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_BULIRSCHSTOER 2L
#undef ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_ROSENBROCK4
#define ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BOOSTSTEPPERTYPE_ROSENBROCK4 3L
/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_initialize
 * Signature: (Lch/ethz/bhepp/ode/BufferOdeAdapter;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DDDI)J
 */
JNIEXPORT jlong JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1initialize
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_prepareStep
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1prepareStep
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_reinitializeOneStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1reinitializeOneStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_integrateOneStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1integrateOneStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_computeInterpolatedSolution
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1computeInterpolatedSolution
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_getCurrentStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1getCurrentStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_getLastStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1getLastStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_setInitStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1setInitStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_setMinStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1setMinStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_setMaxStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1setMaxStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_setStopTime
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1setStopTime
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_quick_reinitialize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1quick_1reinitialize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver
 * Method:    jni_integrate
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_jni_1integrate
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
