/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BoostStepperType */

#ifndef _Included_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BoostStepperType
#define _Included_ch_ethz_bhepp_ode_boost_FixedBoostOdeintSolver_BoostStepperType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
