/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LsodarOdeSolver */

#ifndef _Included_LsodarOdeSolver
#define _Included_LsodarOdeSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LsodarOdeSolver
 * Method:    callbackTest2
 * Signature: ([D)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_LsodarOdeSolver_callbackTest2
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     LsodarOdeSolver
 * Method:    callbackTest
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_LsodarOdeSolver_callbackTest
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
