/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_khammash_nativeode_lsodar_LsodarSolver_Timepoints */

#ifndef _Included_ch_ethz_khammash_nativeode_lsodar_LsodarSolver_Timepoints
#define _Included_ch_ethz_khammash_nativeode_lsodar_LsodarSolver_Timepoints
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
