/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_khammash_nativeode_lsodar_LsodarSolver */

#ifndef _Included_ch_ethz_khammash_nativeode_lsodar_LsodarSolver
#define _Included_ch_ethz_khammash_nativeode_lsodar_LsodarSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_ethz_khammash_nativeode_lsodar_LsodarSolver
 * Method:    jni_initialize
 * Signature: (Lch/ethz/khammash/nativeode/Ode;Lch/ethz/khammash/nativeode/EventFunction;DD)J
 */
JNIEXPORT jlong JNICALL Java_ch_ethz_khammash_nativeode_lsodar_LsodarSolver_jni_1initialize
  (JNIEnv *, jobject, jobject, jobject, jdouble, jdouble);

/*
 * Class:     ch_ethz_khammash_nativeode_lsodar_LsodarSolver
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_ethz_khammash_nativeode_lsodar_LsodarSolver_jni_1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_ethz_khammash_nativeode_lsodar_LsodarSolver
 * Method:    jni_integrate
 * Signature: (JD[DD)D
 */
JNIEXPORT jdouble JNICALL Java_ch_ethz_khammash_nativeode_lsodar_LsodarSolver_jni_1integrate
  (JNIEnv *, jobject, jlong, jdouble, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
