#!/bin/bash

if [ "$3" = "" ]; then
	HOURS=94
else
	HOURS=$3
fi

CONFIGFILE=$1
JOBNAME=$2

CONFIGFILENAME=${CONFIGFILE##*/}
CONFIGBASENAME=${CONFIGFILENAME%.xml}
STDOUTFILENAME=${CONFIGBASENAME}.out
STDERRFILENAME=${CONFIGBASENAME}.err
STDOUTPATH=logs/new/$STDOUTFILENAME
STDERRPATH=logs/new/$STDERRFILENAME

TOTALNCPUS=8
PTILE=4
JVMMAXMEM=128
TOTALMEM=$(( (JVMMAXMEM + 8) * PTILE ))

#bsub -oo $STDOUTPATH -eo $STDERRPATH -J $JOBNAME -n 5 -W $HOURS:00 bash runmpjjob.sh $CONFIGFILE
bsub -oo $STDOUTPATH -eo $STDERRPATH -J $JOBNAME -R "rusage[mem=${TOTALMEM}]" -R "span[ptile=${PTILE}]" -n ${TOTALNCPUS} -W ${HOURS}:00 bash runmpjjob.sh ${JVMMAXMEM} ${CONFIGFILE}

